### ISSUE TITLE
compile marvin_shard_rx.erl failed

### ISSUE THREAD

**Issue by sbaak** [shizzard/marvin#40]
===> Compiling marvin
===> Compiling _build/test/lib/marvin/src/shard/marvin_shard_rx.erl failed
_build/test/lib/marvin/src/shard/marvin_shard_rx.erl:2: undefined callback function code_change/4 (behaviour 'gen_statem')
_build/test/lib/marvin/src/shard/marvin_shard_rx.erl:2: undefined callback function terminate/3 (behaviour 'gen_statem')

**Comment by shizzard** [comment]
code_change and terminate are optional callbacks. Try build with erlang 21+.
