### ISSUE TITLE
Error in the plugin "Gay of the day"

### ISSUE THREAD

**Issue by cooladm1n** [shizzard/marvin#43]
When forming the list of active users and choosing on the basis of it the "Day's gay", the bot itself and temporary users, such as webhooks of Github, are not excluded.

This becomes especially obvious if there are few users on the server or low daily activity for users.
<img width="558" alt="Снимок экрана 2019-03-12 в 13 04 35" src="https://user-images.githubusercontent.com/25665572/54191761-a0e42e00-44c7-11e9-8303-9145274057fa.png">

**Comment by shizzard** [comment]
Not a bug.
