### ISSUE TITLE
Нет реакции на запрос команды, перед которой стоят небуквенные знаки...

### ISSUE THREAD

**Issue by Schreibweiseallianzfuhrer** [shizzard/marvin#52]
...для форматирования текста -> запрос с форматированным текстом не воспринимается.
\~~войс~~
\_\_войс__
\*войс*
\*\*войс**
![image](https://user-images.githubusercontent.com/52926713/61227725-864beb00-a72d-11e9-9f8d-fb56d6082185.png)

**Comment by shizzard** [comment]
Won't fix.
