### ISSUE TITLE
Отсутствие задержки между командами вывода сообщения и генерации ника.

### ISSUE THREAD

**Issue by Schreibweiseallianzfuhrer** [shizzard/marvin#53]
Следствие - вывод текущего ника вместо нового.
![1](https://user-images.githubusercontent.com/52926713/61228321-bb0c7200-a72e-11e9-886d-ea2afbcac4c0.PNG)
![2](https://user-images.githubusercontent.com/52926713/61228323-bb0c7200-a72e-11e9-8e8d-e6488395032e.PNG)
![3](https://user-images.githubusercontent.com/52926713/61228324-bb0c7200-a72e-11e9-82a8-c4890c9091fc.PNG)

**Comment by shizzard** [comment]
For now all API requests are asyncronous.
This plugin performs series of API requests: nickname change (`?ratelimit_group_guild`) and message post (`?ratelimit_group_channel`). These requests are being processed by two separate request queues. It is a perfect race condition.
Proper solution is to implement syncronous API requests.
